### ISSUE TITLE
Can you please update to 1.16.2

### ISSUE THREAD

**Issue by QPCrummer** [jsorrell/skyblock#2]
Can you please update. I am getting an error when trying to load a world.

Here is the error

Description: mouseClicked event handler
org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_32.method_29010(class_32.java:119)
	at net.minecraft.class_32.method_29582(class_32.java:215)
	at net.minecraft.class_32$$Lambda$4840/2144965749.apply(Unknown Source)
	at net.minecraft.class_32.method_26998(class_32.java:178)
	at net.minecraft.class_32.method_29011(class_32.java:61)
	at net.minecraft.class_32$class_5143.method_27013(class_32.java:332)
	at net.minecraft.class_310.method_29599(class_310.java:1682)
	at net.minecraft.class_310$$Lambda$3586/1402766141.apply(Unknown Source)
	at net.minecraft.class_310.method_29604(class_310.java:1909)
	at net.minecraft.class_310.method_29610(class_310.java:1756)
	at net.minecraft.class_310.method_29606(class_310.java:1696)
	at net.minecraft.class_528$class_4272.method_20174(class_528.java:407)
	at net.minecraft.class_528$class_4272.method_20167(class_528.java:287)
	at net.minecraft.class_528$class_4272$$Lambda$3414/756369976.proceed(Unknown Source)
	at net.minecraft.class_405.method_19792(class_405.java:40)
	at net.minecraft.class_405$$Lambda$3418/503722188.onPress(Unknown Source)
	at net.minecraft.class_4185.method_25306(class_4185.java:33)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:149)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:92)
	at net.minecraft.class_312$$Lambda$3082/1305363078.run(Unknown Source)
	at net.minecraft.class_437.method_25412(class_437.java:435)
	at net.minecraft.class_312.method_1601(class_312.java:92)
	at net.minecraft.class_312.method_22686(class_312.java:162)
	at net.minecraft.class_312$$Lambda$2886/1521385264.run(Unknown Source)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_312.method_22684(class_312.java:162)
	at net.minecraft.class_312$$Lambda$2434/1246764203.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:127)
	at net.minecraft.class_310.method_1523(class_310.java:1046)
	at net.minecraft.class_310.method_1514(class_310.java:656)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [skyblock.mixins.json:GeneratorOptionsMixin] from phase [DEFAULT] in config [skyblock.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:643)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:595)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
	... 49 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on addSkyblockGeneratorOptionWhenLoadingProperties could not find any targets matching 'Lnet/minecraft/class_5285;method_28021(Ljava/util/Properties;)Lnet/minecraft/class_5285;' in net.minecraft.class_5285. Using refmap skyblock-refmap.json [PREINJECT Applicator Phase -> skyblock.mixins.json:GeneratorOptionsMixin -> Prepare Injections ->  -> handler$zjf000$addSkyblockGeneratorOptionWhenLoadingProperties(Ljava/util/Properties;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Ljava/lang/String;Ljava/lang/String;ZLjava/lang/String;Ljava/lang/String;J)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:572)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:288)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:275)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:267)
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46)
	at sun.reflect.GeneratedConstructorAccessor10.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:140)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:624)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1247)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 49 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_32.method_29010(class_32.java:119)
	at net.minecraft.class_32.method_29582(class_32.java:215)
	at net.minecraft.class_32$$Lambda$4840/2144965749.apply(Unknown Source)
	at net.minecraft.class_32.method_26998(class_32.java:178)
	at net.minecraft.class_32.method_29011(class_32.java:61)
	at net.minecraft.class_32$class_5143.method_27013(class_32.java:332)
	at net.minecraft.class_310.method_29599(class_310.java:1682)
	at net.minecraft.class_310$$Lambda$3586/1402766141.apply(Unknown Source)
	at net.minecraft.class_310.method_29604(class_310.java:1909)
	at net.minecraft.class_310.method_29610(class_310.java:1756)
	at net.minecraft.class_310.method_29606(class_310.java:1696)
	at net.minecraft.class_528$class_4272.method_20174(class_528.java:407)
	at net.minecraft.class_528$class_4272.method_20167(class_528.java:287)
	at net.minecraft.class_528$class_4272$$Lambda$3414/756369976.proceed(Unknown Source)
	at net.minecraft.class_405.method_19792(class_405.java:40)
	at net.minecraft.class_405$$Lambda$3418/503722188.onPress(Unknown Source)
	at net.minecraft.class_4185.method_25306(class_4185.java:33)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:149)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:92)
	at net.minecraft.class_312$$Lambda$3082/1305363078.run(Unknown Source)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_405
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:435)
	at net.minecraft.class_312.method_1601(class_312.java:92)
	at net.minecraft.class_312.method_22686(class_312.java:162)
	at net.minecraft.class_312$$Lambda$2886/1521385264.run(Unknown Source)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_312.method_22684(class_312.java:162)
	at net.minecraft.class_312$$Lambda$2434/1246764203.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:127)
	at net.minecraft.class_310.method_1523(class_310.java:1046)
	at net.minecraft.class_310.method_1514(class_310.java:656)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.16.2
	Minecraft Version ID: 1.16.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1343304480 bytes (1281 MB) / 2013265920 bytes (1920 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: fabric-loader-0.9.1+build.205-1.16.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Radeon (TM) RX 480 Graphics GL version 4.6.14736 Compatibility Profile Context 20.8.1 27.20.2001.13001, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: file/Wipeout
	Current Language: English (US)
	CPU: 8x AMD FX(tm)-8350 Eight-Core Processor

**Comment by jsorrell** [comment]
Working on it now.

**Comment by jsorrell** [comment]
Check releases for a compatible update.
