### ISSUE TITLE
Cannot generate new skyblock world

### ISSUE THREAD

**Issue by Teeko7** [jsorrell/skyblock#24]
I installed the newest version of fabric for 1.18.1 using the most up to date installer from fabricmc.net, added fabric-carpet, fabric api, and the newest skyblock to the mods folder, added the newest datapack zip file to the datapack folder, changed the level type to level-type=skyblock and I get this error every time I attempt to start the server:

```
java.lang.IllegalStateException: Missing key in ResourceKey[minecraft:root / minecraft:dimension]: ResourceKey[minecraft:worldgen/noise_settings / minecraft:overworld]
at net.minecraft.class_2378.method_31140(class_2378.java:395) ~[server-intermediary.jar:?]
at com.jsorrell.skyblock.gen.SkyBlockGenerationSettings.lambda$createOverworldGenerator$3(SkyBlockGenerationSettings.java:54) ~[skyblock-1.18.1-3.1.1.jar:?]
at net.minecraft.class_3754.<init>(class_3754.java:88) ~[server-intermediary.jar:?]
at net.minecraft.class_3754.<init>(class_3754.java:84) ~[server-intermediary.jar:?]
at com.jsorrell.skyblock.gen.SkyBlockChunkGenerator.<init>(SkyBlockChunkGenerator.java:63) ~[skyblock-1.18.1-3.1.1.jar:?]
at com.jsorrell.skyblock.gen.SkyBlockGenerationSettings.createOverworldGenerator(SkyBlockGenerationSettings.java:52) ~[skyblock-1.18.1-3.1.1.jar:?]
at com.jsorrell.skyblock.gen.SkyBlockGenerationSettings.getSkyBlockDimensionOptions(SkyBlockGenerationSettings.java:31) ~[skyblock-1.18.1-3.1.1.jar:?]
at net.minecraft.class_5285.handler$zni000$addSkyBlockGeneratorOptionWhenLoadingProperties(class_5285.java:543) ~[server-intermediary.jar:?]
at net.minecraft.class_5285.method_28021(class_5285.java:248) ~[server-intermediary.jar:?]
at net.minecraft.class_3806.method_37371(class_3806.java:92) ~[server-intermediary.jar:?]
at net.minecraft.server.Main.main(Main.java:173) [server-intermediary.jar:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.1.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.1.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.13.1.jar:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.13.1.jar:?]
```

I have confirmed this only happens when level-type=skyblock.

**Comment by jsorrell** [comment]
Thanks for the the bug report. I just released a fix.
